### ISSUE TITLE
normal-items doesn't work

### ISSUE THREAD

**Issue by CryLegende** [MrNickax/DropConfirm#1]
Hello, I have a problem with the item list
The normal-items list doesn't work at all and some items in the custom-items list doesn't works too
My config: https://hastebin.com/ikikokusof.yaml
In this one, "GradeYoutuber" does not work but all the other custom items work correctly
And like I said before, normal items don't work at all

I'm using PaperSpigot 1.12

Thank you for your help

**Comment by MrNickax** [comment]
Hello, I'm going to check it out! thanks for reporting it.

**Comment by CryLegende** [comment]
Update: 
I have this error when I drop an item: https://hastebin.com/pacivulaco.log

**Comment by MrNickax** [comment]
It should already be solved, test this version.
https://www.mediafire.com/file/soxlmxvtep4szy4/DropConfirm-1.0.3.jar

**Comment by CryLegende** [comment]
Work fine, thank you ! ^^

**Comment by MrNickax** [comment]
You're welcome! Thanks you for report it.
